comp6001-assessment2-gr07/COMP6001-Assessment2-Gr07/COMP6001-Assessment2-Gr07/Models/ErrorViewModel.cs
using System;

namespace COMP6001_Assessment2_Gr07.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

comp6001-assessment2-gr07/COMP6001-Assessment2-Gr07/COMP6001-Assessment2-Gr07/Models/Model.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.EntityFrameworkCore;
using System.ComponentModel.DataAnnotations;

namespace COMP6001_Assessment2_Gr07.Models
{   
   public class CryptoContext : DbContext
    {
    public CryptoContext(DbContextOptions<CryptoContext> options)
        : base(options)
    { }

    public DbSet<User> Users { get; set; }
    public DbSet<Holding> Holdings { get; set; }
    public DbSet<Wallet> Wallets { get; set; }
    }

    public class User
    {
        public int UserId { get; set; }
        public string Username { get; set; }
        public string Password { get; set; }

    }

    public class Holding
    {
        [Key]
        public int PurchaseId { get; set; }
        public string Symbol { get; set; }
        public double AmountHeld { get; set; }
        public double PurchasePrice { get; set; }
        public string Username { get; set; }

    }
    public class Wallet
    {
        [Key]
        public string Username { get; set; }
        public double CashAvailable { get; set; }
    }
}

comp6001-assessment2-gr07/COMP6001-Assessment2-Gr07/COMP6001-Assessment2-Gr07/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using COMP6001_Assessment2_Gr07.Models;

namespace COMP6001_Assessment2_Gr07.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult About()
        {
            ViewData["Message"] = "Your application description page.";

            return View();
        }


        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

comp6001-assessment2-gr07/COMP6001-Assessment2-Gr07/COMP6001-Assessment2-Gr07/Controllers/UsersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using COMP6001_Assessment2_Gr07.Models;
using System.Diagnostics;
using Microsoft.AspNetCore.Http;

namespace COMP6001_Assessment2_Gr07.Controllers
{

    public class UsersController : Controller
    {
        private readonly CryptoContext _context;
        const string loggedIn1 = "username";

        public UsersController(CryptoContext context)
        {
            _context = context;
        }

        // GET: Users
        public async Task<IActionResult> Index()
        {
            var walletValue = await _context.Wallets.SingleOrDefaultAsync(m => m.Username == HttpContext.Session.GetString(loggedIn1));
            if (walletValue != null)
            {
                ViewBag.Wallet = walletValue.CashAvailable;
                ViewBag.Message = HttpContext.Session.GetString(loggedIn1);
            }
            return View(await _context.Holdings.ToListAsync());
        }
        public async Task<IActionResult> Sell()
        {
            var walletValue = await _context.Wallets.SingleOrDefaultAsync(m => m.Username == HttpContext.Session.GetString(loggedIn1));
            if (walletValue != null)
            {
                ViewBag.Wallet = walletValue.CashAvailable;
                ViewBag.Message = HttpContext.Session.GetString(loggedIn1);
            }
            return View(await _context.Holdings.ToListAsync());
        }

        public IActionResult Register()
        {
            return View();
        }
        public IActionResult Login()
        {
            return View();
        }
        public IActionResult Welcome()
        {
            ViewBag.Message = HttpContext.Session.GetString(loggedIn1);
            return View();
        }
        public async Task<IActionResult> Buy(string test)
        {
            var walletValue = await _context.Wallets.SingleOrDefaultAsync(m => m.Username == HttpContext.Session.GetString(loggedIn1));
            if (walletValue != null)
            {
                ViewBag.Wallet = walletValue.CashAvailable;
                ViewBag.Message = HttpContext.Session.GetString(loggedIn1);
            }
            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Purchase(string buySym, double buyQTY, double buyPrice)
        {
            var user = HttpContext.Session.GetString(loggedIn1);
            var walletConnection = await _context.Wallets.SingleOrDefaultAsync(m => m.Username == HttpContext.Session.GetString(loggedIn1));
            var walletValue = walletConnection.CashAvailable;
            if (ModelState.IsValid)
            {
                if (walletValue > buyQTY*buyPrice)
                {
                    Holding holding = new Holding
                    {
                        Symbol = buySym,
                        AmountHeld = buyQTY,
                        PurchasePrice = buyPrice,
                        Username = user
                    };
                    _context.Add(holding);
                    await _context.SaveChangesAsync();
                    return RedirectToAction(nameof(Buy));
                }
            }
            return Content("<html><body>Insufficient Credit.</body></html>", "text/html");
        }

        // POST: Users/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Register([Bind("UserId,Username,Password")] User user)
        {
            if (ModelState.IsValid)
            {
                _context.Add(user);
                await _context.SaveChangesAsync();
                HttpContext.Session.SetString(loggedIn1, user.Username);
                return RedirectToAction(nameof(Welcome));
            }
            return View(user);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Login(string username, string password)
        {
            if (ModelState.IsValid)
            {
                var userExists = await _context.Users.SingleOrDefaultAsync(m => m.Username == username && m.Password == password);
                if (userExists != null)
                {
                    HttpContext.Session.SetString(loggedIn1, username);
                    return RedirectToAction(nameof(Index));
                }
                else
                {
                    Debug.WriteLine("Username Not Found");
                }
            }
            return RedirectToAction(nameof(Login));
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Begin()
        {
            Wallet newUser = new Wallet();
            newUser.Username = HttpContext.Session.GetString(loggedIn1);
            newUser.CashAvailable = 10000.00;
            _context.Add(newUser);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        // GET: Users/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var user = await _context.Users
                .SingleOrDefaultAsync(m => m.UserId == id);
            if (user == null)
            {
                return NotFound();
            }

            return View(user);
        }

        // POST: Users/Delete/5
        [HttpPost, ActionName("SellCrypto")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> SellCrypto(int id)
        {
            var sale = await _context.Holdings.SingleOrDefaultAsync(m => m.PurchaseId == id);
            _context.Holdings.Remove(sale);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Sell));
        }

        private bool UserExists(int id)
        {
            return _context.Users.Any(e => e.UserId == id);
        }
    }
}

comp6001-assessment2-gr07/COMP6001-Assessment2-Gr07/COMP6001-Assessment2-Gr07/Views/Home/About.cshtml
@{
    ViewData["Title"] = "About";
}
<h2>@ViewData["Title"]</h2>
<h3>@ViewData["Message"]</h3>

<p>Use this area to provide additional information.</p>

comp6001-assessment2-gr07/COMP6001-Assessment2-Gr07/COMP6001-Assessment2-Gr07/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

comp6001-assessment2-gr07/COMP6001-Assessment2-Gr07/COMP6001-Assessment2-Gr07/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - COMP6001_Assessment2_Gr07</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">COMP6001_Assessment2_Gr07</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a asp-area="" asp-controller="Home" asp-action="Index">Home</a></li>
                    <li><a asp-area="" asp-controller="Home" asp-action="About">About</a></li>
                    <li><a asp-area="" asp-controller="Users" asp-action="Login">Login</a></li>
                </ul>
            </div>
        </div>
    </nav>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2017 - COMP6001_Assessment2_Gr07</p>
        </footer>
    </div>

    <!-- jQuery -->
    <script src="https://code.jquery.com/jquery-1.12.4.js"></script>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-K+ctZQ+LL8q6tP7I94W+qzQsfRV2a+AfHIi9k8z8l9ggpc8X+Ytst4yBo/hH+8Fk">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>

comp6001-assessment2-gr07/COMP6001-Assessment2-Gr07/COMP6001-Assessment2-Gr07/Views/Users/Buy.cshtml
@model COMP6001_Assessment2_Gr07.Models.Holding
@{
    ViewData["Title"] = "Index";
}
<!-- Page Content -->
<div class="container">

    <!-- Page Heading/Breadcrumbs -->
    <div class="row">
        <div class="col-lg-12">
            <h1 class="page-header">
                Admin
                <small>Crypto Trade Simulator</small>
            </h1>
            <ol class="breadcrumb">
                <li>
                    <a href="index.php">Home</a>
                </li>
                <li class="active">Admin Index</li>
            </ol>
        </div>
    </div>
    <!-- /.row -->
    <!-- Content Row -->
    <div class="row">
        <!-- Sidebar Column -->
        <div class="col-md-3">
            <div class="list-group">
                <a href="@Url.Action("Index", "Users")" class="list-group-item">Wallet</a>
                <a href="@Url.Action("Buy", "Users")" class="list-group-item">Buy Currencies</a>
                <a href="@Url.Action("Sell", "Users")" class="list-group-item">Sell Currencies</a>
                <form method='POST'>
                    <button class="list-group-item" type="submit" name="logout" value="logout">Logout</button>
                </form>
            </div>
        </div>
        <!-- Content Column -->
        <div class="col-md-9">
            <!-- Content Row -->
            <div class="row">
                <div class="col-sm-12">
                    <div class="panel panel-default">
                        <div class="panel-body">
                            <h2 class="text-center">Marketplace</h2>
                            <h2>Buy</h2>
                            <div class="col-sm-12">
                                    <h4 >Wallet User: </h4><input type="text" value="@ViewBag.Message" name="User" class="text-center"/>
                                    <h4>Wallet Value: </h4><input type="text" value="$@ViewBag.Wallet" name="Wallet" class="text-center"/>
                                    <h5 class="isf">@ViewBag.insufficientFunds</h5>
                                    <div id="cryptoTable"></div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- /.row -->
    <div class="row">
        <div class="col-lg-12">
            <form method='POST'>
                <input class="btn btn-default" type="submit" name="logout" value="logout">
            </form>
        </div>
    </div>
    <hr>

    <!-- Footer -->
    <footer>
        <div class="row">
            <div class="col-lg-12">
                <p>Copyright &copy; Toi Ohomai Institute of Technology</p>
            </div>
        </div>
    </footer>

</div>
<!-- /.container -->

<!-- Modal -->
<div id="myModal" class="modal fade" role="dialog">
    <div class="modal-dialog">

        <!-- Modal content-->
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal">&times;</button>
                <h4 class="modal-title text-center">Purchase</h4>
            </div>
            <div class="modal-body">
                <h4>User: @ViewBag.Message</h4>
                <h4>Wallet: $@ViewBag.Wallet USD</h4>
                <form asp-action="Purchase">
                    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                    <div class="form-group">
                        <label asp-for="Symbol" class="control-label"></label>
                        <input asp-for="Symbol" class="form-control" type="text" name="buySym" id="buySym" value="" readonly />
                        <span asp-validation-for="Symbol" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="PurchasePrice" class="control-label"></label>
                        <input asp-for="PurchasePrice" class="purchasePrice form-control" type="text" name="buyPrice" id="buyPrice" value="" readonly />
                        <span asp-validation-for="PurchasePrice" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label class="control-label">Purchase Quantity</label>
                        <input asp-for="AmountHeld" class="purchaseQTY form-control" type="text" name="buyQTY" id="buyQTY" value="" />
                        <span asp-validation-for="AmountHeld" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label class="control-label">Purchase Value</label>
                        <input class="purchaseValue form-control" type="text" name="buyValue" id="buyValue" value="" readonly /><br />
                    </div>
                    <div class="form-group">
                        <div class="text-center">
                            <input type="submit" class="btn btn-success" value="Proceed!" />
                        </div>
                    </div>
                </form>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
            </div>
        </div>

    </div>
</div>


<script src="http://ajax.googleapis.com/ajax/libs/jquery/1/jquery.min.js"></script>
<script src="https://code.jquery.com/jquery-1.12.4.js"></script>
<script src="/js/cryptoAPIbuy.js"></script>
<script>
    $(document).on("click", ".buyClick", function () {
        var sym = $(this).data('sym');
        var price = $(this).data('price');
        $(".modal-body #buySym").val(sym);
        $(".modal-body #buyPrice").val(price);
    });
</script>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

comp6001-assessment2-gr07/COMP6001-Assessment2-Gr07/COMP6001-Assessment2-Gr07/Views/Users/Index.cshtml
@model IEnumerable<COMP6001_Assessment2_Gr07.Models.Holding>

@{
    ViewData["Title"] = "Index";
}

    <!-- Page Content -->
<div class="container">

    <!-- Page Heading/Breadcrumbs -->
    <div class="row">
        <div class="col-lg-12">
            <h1 class="page-header">
                Admin
                <small>Crypto Trade Simulator</small>
            </h1>
            <ol class="breadcrumb">
                <li>
                    <a href="index.php">Home</a>
                </li>
                <li class="active">Admin Index</li>
            </ol>
        </div>
    </div>
    <!-- /.row -->
    <!-- Content Row -->
    <div class="row">
        <!-- Sidebar Column -->
        <div class="col-md-3">
            <div class="list-group">
                <a href="@Url.Action("Index", "Users")" class="list-group-item">Wallet</a>
                <a href="@Url.Action("Buy", "Users")" class="list-group-item">Buy Currencies</a>
                <a href="" class="list-group-item">Edit Navigation</a>
                <form method='POST'>
                    <button class="list-group-item" type="submit" name="logout" value="logout">Logout</button>
                </form>
            </div>
        </div>
        <!-- Content Column -->
        <div class="col-md-9">
            <!-- Content Row -->
            <div class="row">
                <div class="col-sm-12">
                    <div class="panel panel-default">
                        <div class="panel-body">
                            <h2 class="text-center">Marketplace</h2>
                            <h2>Wallet</h2>
                            <p>Wallet Value: $@ViewBag.Wallet</p>
                            <div class="col-sm-12">
                                <table class="table">
                                    <thead>
                                        <tr>
                                            <th>Currency</th>
                                            <th>Amount Held</th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        @foreach (var item in Model)
                                        {
                                            if (item.Username == ViewBag.Message)
                                            {
                                            <tr>
                                                <td>
                                                    @Html.DisplayFor(modelItem => item.Symbol)
                                                </td>
                                                <td>
                                                    @Html.DisplayFor(modelItem => item.AmountHeld)
                                                </td>
                                            </tr>
                                            }
                                        }
                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- /.row -->
    <div class="row">
        <div class="col-lg-12">
            <form method='POST'>
                <input class="btn btn-default" type="submit" name="logout" value="logout">
            </form>
        </div>
    </div>
    <hr>

    <!-- Footer -->
    <footer>
        <div class="row">
            <div class="col-lg-12">
                <p>Copyright &copy; Toi Ohomai Institute of Technology</p>
            </div>
        </div>
    </footer>

</div>
<!-- /.container -->

comp6001-assessment2-gr07/COMP6001-Assessment2-Gr07/COMP6001-Assessment2-Gr07/Views/Users/Login.cshtml
@model COMP6001_Assessment2_Gr07.Models.User

@{
    ViewData["Title"] = "Login";
}

<div class="container">
    <!-- Page Heading/Breadcrumbs -->
    <div class="row">
        <div class="col-lg-12">
            <h1 class="page-header">
                Login
                <small>Crypto Labs</small>
            </h1>
            <ol class="breadcrumb">
                <li>
                    <a href="index.html">Home</a>
                </li>
                <li class="active">Login Page</li>
            </ol>
        </div>
    </div>
    <!-- /.row -->
    <!-- Content Row -->
    <div class="row">
        <div class="col-sm-12">
            <div class="panel panel-default">
                <div class="panel-body">
                    <h3>Please enter your details to login</h3>
                    <form asp-action="Login">
                        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                        <div class="form-group">
                            <label asp-for="Username" class="control-label"></label>
                            <input asp-for="Username" class="form-control" />
                            <span asp-validation-for="Username" class="text-danger"></span>
                        </div>
                        <div class="form-group">
                            <label asp-for="Password" class="control-label"></label>
                            <input asp-for="Password" class="form-control" />
                            <span asp-validation-for="Password" class="text-danger"></span>
                        </div>
                        <div class="form-group">
                            <div class="text-center"><input type="submit" value="Login" class="btn btn-success" /><br />
                            <a asp-area="" asp-controller="Users" asp-action="Register">or click here to Register</a></div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
    <!-- /.row -->
    <hr>

    <!-- Footer -->
    <footer>
        <div class="row">
            <div class="col-lg-12">
                <p>Copyright &copy; Toi Ohomai Institute of Technology</p>
            </div>
        </div>
    </footer>

</div>
<!-- /.container -->

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

comp6001-assessment2-gr07/COMP6001-Assessment2-Gr07/COMP6001-Assessment2-Gr07/Views/Users/Register.cshtml
@model COMP6001_Assessment2_Gr07.Models.User

@{
    ViewData["Title"] = "Create";
}

<h2>Create</h2>

<h4>User</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Register">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Username" class="control-label"></label>
                <input asp-for="Username" class="form-control" />
                <span asp-validation-for="Username" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Password" class="control-label"></label>
                <input asp-for="Password" class="form-control" />
                <span asp-validation-for="Password" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Register" class="btn btn-default" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

comp6001-assessment2-gr07/COMP6001-Assessment2-Gr07/COMP6001-Assessment2-Gr07/Views/Users/Sell.cshtml
@model IEnumerable<COMP6001_Assessment2_Gr07.Models.Holding>

@{
    ViewData["Title"] = "Index";
}

<!-- Page Content -->
<div class="container">

    <!-- Page Heading/Breadcrumbs -->
    <div class="row">
        <div class="col-lg-12">
            <h1 class="page-header">
                Admin
                <small>Crypto Trade Simulator</small>
            </h1>
            <ol class="breadcrumb">
                <li>
                    <a href="index.php">Home</a>
                </li>
                <li class="active">Admin Index</li>
            </ol>
        </div>
    </div>
    <!-- /.row -->
    <!-- Content Row -->
    <div class="row">
        <!-- Sidebar Column -->
        <div class="col-md-3">
            <div class="list-group">
                <a href="@Url.Action("Index", "Users")" class="list-group-item">Wallet</a>
                <a href="@Url.Action("Buy", "Users")" class="list-group-item">Buy Currencies</a>
                <a href="@Url.Action("Sell", "Users")" class="list-group-item">Sell Currencies</a>
                <form method='POST'>
                    <button class="list-group-item" type="submit" name="logout" value="logout">Logout</button>
                </form>
            </div>
        </div>
        <!-- Content Column -->
        <div class="col-md-9">
            <!-- Content Row -->
            <div class="row">
                <div class="col-sm-12">
                    <div class="panel panel-default">
                        <div class="panel-body">
                            <h2 class="text-center">Marketplace</h2>
                            <h2>Buy</h2>
                            <p>Wallet Value: $@ViewBag.Wallet</p>
                            <div class="col-sm-12">
                                <table class="table">
                                    <thead>
                                        <tr>
                                            <th>Currency</th>
                                            <th>Amount Held</th>
                                            <th>Sell</th>
                                        </tr>
                                    </thead>
                 
                                        <tbody>

                                            @foreach (var item in Model)
                                            {
                                                var id = item.PurchaseId;
                                                if (item.Username == ViewBag.Message)
                                                {
                                                    <tr>
                                                        <td>
                                                            @Html.DisplayFor(modelItem => item.Symbol)
                                                        </td>
                                                        <td>
                                                            @Html.DisplayFor(modelItem => item.AmountHeld)
                                                        </td>
                                                        <td>
                                                            @Html.DisplayFor(modelItem => item.PurchasePrice)
                                                        </td>
                                                        <td>
                                                            <form asp-action="SellCrypto">
                                                                <input type="hidden" name="id" id="id" value="@id" />
                                                                <input type="submit" class="sellClick btn btn-success" data-toggle="modal" data-target="#myModal" value="Sell"/>
                                                            </form>
                                                        </td>
                                                    </tr>
                                                }
                                            }
                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- /.row -->
    <div class="row">
        <div class="col-lg-12">
            <form method='POST'>
                <input class="btn btn-default" type="submit" name="logout" value="logout">
            </form>
        </div>
    </div>
    <hr>

    <!-- Footer -->
    <footer>
        <div class="row">
            <div class="col-lg-12">
                <p>Copyright &copy; Toi Ohomai Institute of Technology</p>
            </div>
        </div>
    </footer>

</div>
<!-- /.container -->

<script>
    $(document).on("click", ".sellClick", function () {
        var sym = "22"
        $(".modal-body #sellSym").val(sym);
        $(".modal-body #sellPrice").val(price);
        $(".modal-body #sellQTY").val(price);
    });
</script>